[package]
name = "aes"
version = "0.1.0"
authors = ["Maurycy Z <10maurycy10@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
